# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23b65d16832bab0f417a940539b170151143638979e35e385fb002bf1935af8f078111d76f5a6542834d06e2b3cd07b5d06593246ab4e730529c35cafe1d16b9

test:
  secret_key_base: f04ad556ff3ba667af5ebb50bcb1de0628c8adb8a8221bff72e6ac1be654c040e4c0b26fc4f6af7754a0b4201e3cfcccb7b48e436ebc60e5bf217919e7893ce2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
